 INSERT INTO room_type (id, name, guest_capacity, price) VALUES (1,'Single', 1, 80);
 INSERT INTO room_type (id, name, guest_capacity, price) VALUES (2, 'Double', 2, 120);
 INSERT INTO room_type (id, name, guest_capacity, price) VALUES (3, 'Family', 4, 200);
 INSERT INTO room_type (id, name, guest_capacity, price) VALUES (4, 'Suite', 4, 300);


INSERT INTO room (number, type) VALUES (101, 1);
INSERT INTO room (number, type) VALUES (102, 1);
INSERT INTO room (number, type) VALUES (103, 1);
INSERT INTO room (number, type) VALUES (104, 1);
INSERT INTO room (number, type) VALUES (105, 2);
INSERT INTO room (number, type) VALUES (106, 2);
INSERT INTO room (number, type) VALUES (201, 1);
INSERT INTO room (number, type) VALUES (202, 1);
INSERT INTO room (number, type) VALUES (203, 1);
INSERT INTO room (number, type) VALUES (204, 2);
INSERT INTO room (number, type) VALUES (205, 2);
INSERT INTO room (number, type) VALUES (206, 2);
INSERT INTO room (number, type) VALUES (301, 2);
INSERT INTO room (number, type) VALUES (302, 2);
INSERT INTO room (number, type) VALUES (303, 3);
INSERT INTO room (number, type) VALUES (304, 4);
INSERT INTO room (number, type) VALUES (305, 1);
INSERT INTO room (number, type) VALUES (306, 2);
INSERT INTO room (number, type) VALUES (401, 1);
INSERT INTO room (number, type) VALUES (402, 2);
INSERT INTO room (number, type) VALUES (403, 3);
INSERT INTO room (number, type) VALUES (404, 4);
INSERT INTO room (number, type) VALUES (405, 1);
INSERT INTO room (number, type) VALUES (406, 4);